### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GioviQ** [BlazingOrchard/Blazing-Orchard#8]
Hi, I know OrchardCMS and I find this project very interesting, because I am moving my skills to Blazor developing for starter kit https://github.com/enkodellc/blazorboilerplate.

In future I could integrate Blazing-Orchard, but BlazorBoilerplate has a feature to set Blazor mode for each tenant. So you can have a WASM tenant and a Blazor Server tenant.

I suppose this could be an issue for integration, isn't it?

**Comment by OrchardSkills** [comment]
I'm not sure I understand your question. Orchard Core already has multi tenant capabilities?  Are you proposing to implement  multi tenant capabilities with the Blazor Boilerplate?

**Comment by GioviQ** [comment]
But can you set Blazor hosting model for each tenant?

**Comment by OrchardSkills** [comment]
No. Orchard Core consists of two different targets: Orchard Core Framework: An application framework for building modular, multi-tenant applications on ASP.NET Core. Orchard Core CMS: A Web Content Management System (CMS) built on top of the Orchard Core Framework. It utilizes Razor and Liquid pages. The application framework for building modular, multi-tenant applications is not based on the Blazor hosting Model. The current server/client example here is a headless CMS solution. Both the Orchard Core CMS Server Application and the Blazor Server/WASM are separate applications and both must be running.  As of today, one disadvantage that Blazor has is that it's still in its infancy. It needs time to mature. Don't get me wrong. I believe Blazor is an up and coming technology that can't be ignored. Switching the Orchard Core Framework to utilize the Blazor hosting model would be a significant task. It's currently not on the Orchard Core Roadmap. 

I believe utilizing the Blazor Hosting Model would be a great project to explore. Your input would be welcomed. Maybe we can create an architecture document and requirements to define the objectives.

**Comment by GioviQ** [comment]
I misunderstood Blazing-Orchard was OrchardCore migration to Blazor...
